### ISSUE TITLE
Enhancement Changes

### ISSUE THREAD

**Issue by ZikaZaki** [megha-n-bodke/womenhealth.github.io#1]
# Enhancement Changes

Hi, @megha-n-bodke, you did a great job so far, but there are some **enhancement** changes you need to implement. Here is a list of the changes needed to be implemented:
- [ ] The `menu` button `size` is too big. Therefore, you need to make it a little bit smaller. You can set it to `width="32px" height="32px"`.
- [ ] The `opacity` of the **menu-background** is too much. Hence the user cannot differentiate between the menu content and the background content. So please adjust it.
- [ ] The **location text** is hardly recognized as shown in the attached screenshot below. So please adjust the `text-color`.
![location-txt](https://user-images.githubusercontent.com/101884291/183747755-fe3b2e68-1ad4-4071-9996-c553e568913a.PNG)

**Comment by megha-n-bodke** [comment]
Thanks for the suggestions, I would like to implement the changes, as it will improve my skills.
